//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGRO_BASKET
    {
        public decimal ID { get; set; }
        public decimal QANTITY { get; set; }
        public System.DateTime DATA_START { get; set; }
        public decimal ID_PRODUCT { get; set; }
    
        public virtual AGRO_PRODUCT AGRO_PRODUCT { get; set; }
    }
}
