//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGRO_ORDER
    {
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public decimal QANTITY { get; set; }
        public decimal PRICE_ONE { get; set; }
        public decimal ID_CONTRACT { get; set; }
    
        public virtual AGRO_CONTRACT AGRO_CONTRACT { get; set; }
    }
}
